language: python
python:
  - "3.6.0"

install:
  - pip install -r requirements.txt

script: python -m unittest

after_success:
  - coverage run -m unittest discover
  - coverage report
  - codecov -t c4989a8c-a542-4fd1-bb6b-98a93caf0285
